In [4]:
import numpy as np
import pandas as pd

In [5]:
pd.__version__

'3.0.6'

In [8]:
df = pd.read_csv("car_fuel_efficiency_2026.csv")

In [9]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [10]:
df.shape

(10000, 11)

In [13]:
df["fuel_type"].unique()

<StringArray>
['Gasoline', 'Diesel', 'Hybrid']
Length: 3, dtype: str

In [14]:
df.isna().sum()

model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors                0
engine_displacement      0
num_cylinders            0
horsepower             877
vehicle_weight           0
acceleration           264
fuel_efficiency_mpg      0
dtype: int64

In [15]:
df["fuel_efficiency_mpg"].max()

np.float64(41.2)

In [16]:
df["horsepower"].median()

np.float64(254.0)

In [17]:
median_before = df["horsepower"].median()
print(median_before)

254.0

In [18]:
df["horsepower"].mode()

0    252.0
Name: horsepower, dtype: float64

In [19]:
most_frequent = df["horsepower"].mode()[0]
print(most_frequent)

252.0

In [23]:
df["horsepower"] = df["horsepower"].fillna(most_frequent)

In [24]:
df["horsepower"].isna().sum()

np.int64(0)

In [25]:
median_after = df["horsepower"].median()
print(median_after)

252.0

In [26]:
if median_after > median_before:
    print("Yes, it increased")
elif median_after < median_before:
    print("Yes, it decreased")
else:
    print("No")

Yes, it decreased

In [28]:
df.head()

,model_year,origin,fuel_type,drivetrain,num_doors,engine_displacement,num_cylinders,horsepower,vehicle_weight,acceleration,fuel_efficiency_mpg
0,2006,Europe,Gasoline,Front-wheel drive,4,2180,6,243.0,3870,NaN,31.9
1,2008,Europe,Diesel,Front-wheel drive,4,2390,6,272.0,4210,NaN,31.3
2,1996,Asia,Gasoline,Front-wheel drive,5,2320,6,267.0,4240,17.3,27.5
3,1989,Europe,Gasoline,Front-wheel drive,4,2130,6,258.0,4490,18.7,28.5
4,1994,USA,Diesel,Front-wheel drive,3,2580,7,304.0,4510,17.5,31.0

In [29]:
df["vehicle_weight"].sum()

np.int64(42867540)

In [30]:
# 1. Select cars from Asia
asia = df[df["origin"] == "Asia"]

# 2 & 3. Select columns and first 7 rows
X = asia[["vehicle_weight", "model_year"]].head(7)

# 4. Convert to NumPy array
X = X.to_numpy()

# 5. Calculate XTX
XTX = X.T @ X

# 6. Invert XTX
XTX_inv = np.linalg.inv(XTX)

# 7. Create y
y = np.array([1100, 1300, 800, 900, 1000, 1100, 1200])

# 8. Calculate w
w = XTX_inv @ X.T @ y

# 9. Sum w
print("w =", w)
print("sum =", w.sum())

w = [0.13644777 0.2327492 ]
sum = 0.3691969690492522